#   /$$      /$$                  /$$$$$$                      /$$          
#  | $$$    /$$$                 /$$__  $$                    | $$          
#  | $$$$  /$$$$ /$$   /$$      | $$  \__/  /$$$$$$  /$$   /$$| $$  /$$$$$$$
#  | $$ $$/$$ $$| $$  | $$      |  $$$$$$  /$$__  $$| $$  | $$| $$ /$$_____/
#  | $$  $$$| $$| $$  | $$       \____  $$| $$  \ $$| $$  | $$| $$|  $$$$$$ 
#  | $$\  $ | $$| $$  | $$       /$$  \ $$| $$  | $$| $$  | $$| $$ \____  $$
#  | $$ \/  | $$|  $$$$$$$      |  $$$$$$/|  $$$$$$/|  $$$$$$/| $$ /$$$$$$$/
#  |__/     |__/ \____  $$       \______/  \______/  \______/ |__/|_______/ 
#                /$$  | $$                                                  
#               |  $$$$$$/                                                  
#                \______/                                                   
#
# --------------------------------------------------------------------------
#
#  Release: 2.0.0
#
#  Spigot: https://www.spigotmc.org/resources/mysouls.86749/
#  Github: https://github.com/arthurfiorette/mysouls
#  Twitter: https://twitter.com/arthurfiorette
#  Steam: https://steamcommunity.com/profiles/76561198850668121
#  
#  In any use of this plugin, I would love it if I had any credit
#  relating to the plugin. Good game!
#
#  This file contains the general settings of the plugin, 
#  customizing it makes the game rules of the plugin
#  different from the others.
#

# All business rules
rules:
  souls:
    initial: 2

# Plugin customization, changing this values does not alter the final behaviour
customization:
  heads:
  coin: http://textures.minecraft.net/texture/35b116dc769d6d5726f12a24f3f186f839427321e82f4138775a4c40367a49
  soul: http://textures.minecraft.net/texture/35b116dc769d6d5726f12a24f3f186f839427321e82f4138775a4c40367a49
  trophy: http://textures.minecraft.net/texture/e34a592a79397a8df3997c43091694fc2fb76c883a76cce89f0227e5c9f1dfe

# Internal plugin configuration.
internal:
  cache:
    # The max amount of entities in the cache, once this number is passes, the last item is evicted.
    max-entities: 256

    # The amount of partitions between this cache. Do not change.
    concurrency-level: 4

    # Time to persist the entity after it's read.
    eviction:
      # Choose between NANOSECONDS, MICROSECONDS, MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS 
      unit: SECONDS
      # The unit duration, example 5 Seconds
      duration: 5
