name: MySouls
description: The best soul pvp plugin for Spigot 1.8
main: com.github.hazork.building.mysouls.MySouls
author: Hazork
version: 1.3.0
commands:
  mysouls:
    aliases: [ms, souls]
    description: The principal and only command from this plugin.
    usage: /<command> [arguments]